name: "Confluence Publisher"

# 動くきっかけ(push のタイミングで動作)
on:
  workflow_dispatch:  # 画面で実行ボタン押下
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'scripts/sync_to_confluence.py'
      - '.github/workflows/confluence.yml'

# 動かす内容
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Sync Markdown to Confluence
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_USER_NAME: ${{ secrets.CONFLUENCE_USER_NAME_SECRET }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN_SECRET }}
          CONFLUENCE_PARENT_ID: ${{ secrets.CONFLUENCE_PARENT_ID }}
          CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY || 'DOCS' }}
        run: |
          python scripts/sync_to_confluence.py